manual/source/classes/index.rst
manual/source/ref_doc.rst

Add classes index

---

manual/CMakeLists.txt
manual/source/classes/applications/CMakeLists.txt
manual/source/classes/base_classes/CMakeLists.txt
manual/source/classes/contributed_definitions/CMakeLists.txt

Pete, does this work refs #360

Copy over changed files on make, hopefully gets incremental builds working

---

base_classes/NXentry.nxdl.xml

In agreement with NXbase class
fixes #395

change mime_type to type

---

base_classes/NXdetector.nxdl.xml

Correct typos

---

Makefile_old
nxdl.xsd
nxdlTypes.xsd

remove SVN keywords from files in use

---

nxdl.xsd

This allows generating code to handle multiple arbitrarily named fields, and also, handle associated fields where their names follow as simple substitution pattern. It is a possible solution for #399

Add nameType tag attribute

---

manual/source/applying-nexus.rst
manual/source/classes/base_classes/index.rst

The main sections actually concerning base classes and application definitions
were not worded as strongly. So we are toning it down here.
Refs #418

address most obvious cases claiming base class completeness

---

jenkins_build

Need recursive copy now

---

contributed_definitions/NXspecdata.nxdl.xml
manual/source/utilities.rst

proposed application definition for data from SPEC

---

contributed_definitions/NXreflections.nxdl.xml

This is the candidate NXreflections definition file to be reviewed at NIAC 2016.

Candidate NXreflections definition file, authored by @jmp1985

---

Makefile
base_classes/NXtransformations.nxdl.xml
manual/source/conf.py

Issue 484: math in NXtransformations

---

contributed_definitions/NXcanSAS.nxdl.xml

NXcanSAS  restored and revised

---

base_classes/NXdata.nxdl.xml
base_classes/NXentry.nxdl.xml
manual/source/applying-nexus.rst
manual/source/datarules.rst
manual/source/examples/h5py/index.rst
manual/source/examples/h5py/writer_1_3.rst
manual/source/examples/h5py/writer_2_1.rst
manual/source/introduction.rst
manual/source/preface.rst
manual/source/rules.rst

fixes #493:
NIAC2016
- http://wiki.nexusformat.org/NIAC2016
- https://github.com/nexusformat/NIAC/issues/16

NXdata is now optional, as of NIAC2016

---

.travis.yml
utils/test_nxdl.py

travis-ci integration complete

Unit tests 512

---

applications/NXmx.nxdl.xml
base_classes/NXtransformations.nxdl.xml
nxdl.xsd

* #546: minOccurs suggests possible multiple use but this is not allowed for attributes.  Replaces with new ``required`` attribute

Issue 546 minOccurs=0 to required=false

---

nxdl.xsd

adds to the documentation as described in #571

fixes #571

---

applications/NXsas.nxdl.xml
applications/NXsastof.nxdl.xml

clarified initial documentation, made text similar in both NXsas and NXsastof

fixes #560: changes to documentation only

---

base_classes/NXinstrument.nxdl.xml
base_classes/NXtransformations.nxdl.xml

define diffractometer in NXinstrument -- issue 632

---

manual/source/defs_intro.rst
manual/source/design.rst
manual/source/examples/code_napi.rst
manual/source/examples/code_native.rst
manual/source/examples/epics/index.rst
manual/source/examples/lrmecs/index.rst
manual/source/examples/matlab/index.rst
manual/source/fileformat.rst
manual/source/napi-java.rst

resolve Sphinx errors

---

manual/source/applying-nexus.rst
manual/source/examples/h5py/index.rst
manual/source/installation.rst
manual/source/introduction-napi.rst
manual/source/introduction.rst

change "guess" highlight to language-specific

---

impatient-guide/index.rst
manual/source/design.rst
manual/source/examples/hierarchy-processed.txt
manual/source/rules.rst

In order to be compatible with the NXparameters base class I've changed NXparameter to NXparameters

change NXparameter to NXparameters

---

utils/test_nxdl2rst.py

certain unit tests had failed

---

nxdlTypes.xsd

cleanup in nxdl.xsd

---

nxdl.xsd
nxdlTypes.xsd
utils/nxdl_desc2rst.py
utils/types2rst.py

Refs #699
Remove alias in schema, add links to schema documentation,
unescape HTML tags in doc generator

Remove some references to NAPI for #699

---

contributed_definitions/NXcxi_ptycho.nxdl.xml

Hi @vasole,@prjemian and @markbasham,
In response to #647, @vincefn and I have been talking over the past couple of days.
We have agreed that making these fields optional rather than mandatory is a good idea and will probably improve uptake of the definition. Since the structure of the definition doesn't change, this is a backwards compatible change.
Let me know if theres anything else that is needed to get this into the main repo.
Thanks,
Aaron

Reduce number of mandatory fields in NXcxi_ptycho

---

manual/source/examples/code_native.rst
manual/source/examples/nxh5read.c
manual/source/examples/nxh5write.c

Attribute code refactored, updated for HDF 1.8.0, new axes syntax
fix #665

Update example for new axes syntax and for HDF 1.8.0 and above

---

manual/source/faq.rst

FAQ that help clarify the nature of application definitions to fix #697

clarify the nature of application definitions

---

applications/NXmx.nxdl.xml

From code camp, clarify NXmx/NXdetector depends_on field.

---

manual/source/examples/index.rst
manual/source/utilities.rst

Citations of various API implementations from the community to fix #630
Reviewers chosen from those who made contributions to #693 Also inviting @toqduj to comment.
Note this is for the milestone that results in next release of NXDL which *will* happen on 2020-01-31.

cite API contributions

---

applications/NXstxm.nxdl.xml

added type="NX_FLOAT"

---

base_classes/NXreflections.nxdl.xml

Fixes #727
Lots of whitespace here.  Look at commit 7b7e08b to see the changes.

NXreflections tidy

---

applications/NXmx.nxdl.xml

Add note to clarify that variants can be used to specify multiple usecases in NXmx's NXbeam

---

nxdl.xsd

Also fix mixed indentations and remove trailing spaces

Fix spelling in schema definition

---

applications/NXmx.nxdl.xml
base_classes/NXdetector.nxdl.xml
base_classes/NXdetector_group.nxdl.xml
base_classes/NXdetector_module.nxdl.xml

clarify hierarchy of different detector group base classes

---

base_classes/NXdetector.nxdl.xml

Remove X, Y and Z from NXdetector symbol table

---

base_classes/NXsample.nxdl.xml

fixes #816
This is per approved vote from NIAC2018

deprecate 2 fields in NXsample

---

base_classes/NXdata.nxdl.xml

fixes #815 per NIAC2018 approved vote

add NXdata/@auxiliary_signals  attribute

---

manual/source/examples/h5py/writer_1_3.rst
manual/source/examples/h5py/writer_2_1.rst
manual/source/utilities.rst
manual/source/validation.rst

add nexpy/nexusformat python package to utilities page 

---

manual/source/datarules.rst
nxdlTypes.xsd

recommend providing time zone in NX_DATE_TIME

---

contributed_definitions/NXsnsevent.nxdl.xml
contributed_definitions/NXsnshisto.nxdl.xml

NXsnsevent and NXsnshisto: deprecate _error fields

---

manual/source/design.rst

Indicate that CIF is the preferred geometry style now

---

.gitignore
base_classes/NXdata.nxdl.xml
nxdl.xsd

resolve problems identified when building the Sphinx documentation

---

applications/NXmx.nxdl.xml

NXMX:  incident_wavelength_weight  --->   incident_wavelength_weights

---

manual/source/datarules.rst

fixes #814 as approved at [NIAC2018](https://www.nexusformat.org/NIAC2018Minutes.html)

Add _mask as a reserved suffix.

---

manual/source/mailinglist.rst

clarify in manual about mailing list subscriptions 

---

nxdl.xsd

fixes #759
the first paragraph should be be one line for use on summary page

group doc element needs more description

---

manual/source/design.rst

clarify notation of tree structure

---

applications/NXmx.nxdl.xml
manual/source/conf.py

Correct indentation in NXmx and raise maxdepth list as some application definitions are very deeply nested

Fix latex build for #828

---

manual/source/design.rst
nxdl.xsd

add 5 interpretation attribute values for color images

---

utils/nxdl2rst.py

DOC: clarify target value is a suggestion

---

contributed_definitions/NXspecdata.nxdl.xml

Marks NXspecdata as deprecated.

---

manual/source/datarules.rst

fixes #769 and fixes #781 and fixes #831

reserved prefixes for names

---

base_classes/NXroot.nxdl.xml

fixes #789
Holding as draft PR until review & acceptance by NIAC

add @creator_version

---

applications/NXmx.nxdl.xml

fixes #838 per https://manual.nexusformat.org/defs_intro.html#overview-of-nexus-definitions

NXmx: add version attribute

---

base_classes/NXdetector.nxdl.xml

NXdetector: move start_time & end_time OUT of efficiency group

---

base_classes/NXentry.nxdl.xml

As proposed and accepted under https://github.com/nexusformat/NIAC/issues/80

Add entry_identifier_uuid to NXentry

---

manual/source/datarules.rst

As discussed in https://github.com/nexusformat/NIAC/issues/80

Add BLUESKY_ as a reserved prefix

---

CHANGES.rst
utils/create_release_notes.py
utils/dev_create_release_notes.py
utils/nxdl2rst.py

switch repo default branch from master to main

---

base_classes/NXtransformations.nxdl.xml

Make the vector attribute mandatory, add note on offset usage.

Clarify NXtransformations to fix #885

---

base_classes/NXsource.nxdl.xml

Addition of X-ray MetalJet to the enumerated list of source types within NXsource

Suggested change to NXsource - Issue #934

---

manual/source/faq.rst

repair item numbers in FAQ

---

.github/workflows/syntax-checks.yml
environment.yml

remove `environment.yml` file

---

nxdlTypes.xsd

add NX_COUNT

---

applications/NXmx.nxdl.xml

Update NXmx instrument's short_name to be optional to match NXmx source's short_name

---

applications/NXtofraw.nxdl.xml

fix name of azimuthal angle in doc string

---

BUILDING.rst
CHANGES.rst
requirements.txt

py3.7 minimum

---

manual/source/examples/index.rst

fixes https://github.com/nexusformat/NIAC/issues/91

clarify that NeXus utilities are not directly code

---

README.md

Add badges for CI, CD and license:

add badges for license and CI/CD

---

manual/source/datarules.rst

reserve DECTRIS_ prefix

---

base_classes/NXsample.nxdl.xml

removed NXlog group called temperature

---

applications/NXmx.nxdl.xml

@phyy-nx This is a PR to your branch, not the main branch. It implements the fixes I proposed.

fix flux units and improve docs

---

.github/workflows/publish-sphinx.yml
.github/workflows/syntax-checks.yml

execute CI only for the main branch

---

applications/NXarpes.nxdl.xml

ARPES: make numbers number types

---

manual/source/applying-nexus.rst

Appdefs cannot force NXentry usage but can advise

---

manual/Makefile
manual/source/Makefile
manual/source/classes/Makefile
manual/source/classes/applications/Makefile
manual/source/classes/base_classes/Makefile
manual/source/classes/contributed_definitions/Makefile

Propagate cleaning to all sub-directories, remove generated index.rst, remove copied definitions sub-directories

Fix Makefiles to clean up properly

---

base_classes/NXpinhole.nxdl.xml

remove duplicate group from NXpinhole

---

base_classes/NXbending_magnet.nxdl.xml
manual/source/conf.py

add sphinx todo extension

---

nxdlTypes.xsd

nxdlTypes.xsd: unit restrictions should be based on xs:string

---

manual/source/design.rst
manual/source/introduction.rst

Cleanup introduction of links element

---

.github/env-workflow.yml
requirements.txt
utils/nxdl2rst.py

remove pyRestTable requirement

---

.github/workflows/publish-sphinx.yml
CHANGES.rst

Changes the documented release version
- close #1128

DOC v2022.06rc1

---

utils/nxdl2rst.py

add NeXus version metadata to vocabulary file

---

Makefile

Use style file when creating latex index

---

.github/workflows/publish-sphinx.yml

- Closes https://github.com/nexusformat/definitions/issues/1154
- Alternative to https://github.com/nexusformat/definitions/pull/1157

add CNAME to the result of a sphinx HTML build

---

.github/workflows/publish-sphinx.yml
manual/source/CNAME
manual/source/conf.py

Closes #1154
This solution works locally and does not require manual CNAME creation.

create CNAME in build result by sphinx so CI works

---

utils/nxdl2rst.py

Define use_application_defaults only once

---

CHANGES.rst
manual/source/history.rst

Document the changes for 2022.06 release

---

applications/NXmx.nxdl.xml

Make incident_polarisation_stokes optional

---

applications/NXcanSAS.nxdl.xml
contributed_definitions/NXsnsevent.nxdl.xml
contributed_definitions/NXsnshisto.nxdl.xml

Make deprecated fields in some application definitions optional

---

manual/source/utilities.rst

Note more tools for HDF5 files

---

dev_tools/docs/nxdl.py

add closing parenthesis in "suggested target" text

---

contributed_definitions/NXxpcs.nxdl.xml

- close #1004
@ambarb, @tacaswell: Please comment.

NXxpcs: clarify use of entry_identifier, entry_identifier_uuid, and scan_number

---

CHANGES.rst

update the change history

---

manual/source/utilities.rst

repair broken URL under HDF5 File Tools

---

contributed_definitions/NXxpcs.nxdl.xml

- close #1204
@tlcfem, @ambarb : your review comments are invited

NXxpcs: use a valid units type

---

manual/source/examples/epics/index.rst

fix reST syntax

---

.github/workflows/ci.yaml

Remove 3.7 and add 3.11 and fixes #1259

Update python versions for #1259

---

.github/workflows/ci.yaml

Remove repeated sphinx build and deploy with single action to fix #1288

Fix deployment in CI

---

base_classes/NXtransformations.nxdl.xml

the value of a directional NXtransformations field is ignored

---

applications/NXmx.nxdl.xml

NXmx: make countrate_correction_lookup_table optional

---

.github/workflows/ci.yaml

update GHA checkout to current version

---

base_classes/NXaperture.nxdl.xml

In the 2024-01-17 telco, we found this typo

DOC typo NXaperture

---

utils/create_release_notes.py

Fix timestamp parsing from updated pygithub to 2.1.0+

---

CHANGES.rst

Also publish new version of manual

Update CHANGES with release v2024.02

---

dev_tools/docs/nxdl.py

NXclass status in the docs: make it clear when it is a contribution

---

base_classes/NXbeam.nxdl.xml

Remove nameType=any from reference_plane as this name is used literally

---

dev_tools/apps/manual_app.py

This was copy&pasted from impatient_app but not modified. manual_app is for testing/building the NeXus documentation.

fix CLI doc

---

base_classes/NXtransformations.nxdl.xml

Fix typo in NXtransformations.nxdl.xml

---

applications/NXellipsometry.nxdl.xml

fix uppercase notation in `NXellipsometry`
