- CMakeLists.txt
Removed the LANGUAGES keyword from the project command.
Hoping to get Jenkins to build successfully before the weekend.
> Solving problem with missing CMake variable

- base_classes/NXtransformations.nxdl.xml
#547: defines ``vector_units`` attribute
> fixes #547: defines ``vector_units`` attribute for NXtransformations

- contributed_definitions/NXreflections.nxdl.xml
Action items from minutes completed:
-H,K,L change to NX_number for incommensurate structures
-Discussion on flags, change to bitfield, no enum for efficiency
-Expand the description of partiality
-Need to keep mm and pixel positions because of parallax
-Write out predicted and observed
-Drop the mm in names, rather use units
-bounding_box as array, document the usage
-Spell out background
-Drop the val on the intensities, keep the _var version
code is not in place we defer it for now.
-Add polar_angle and azimuthal_angle
TODO
-Need documentation for polar_angle and azimuthal_angle
-Need to add some examples of flags. Would like to use the DIALS flags.
Deferred:
-overlaps is a list of overlapped reflections. This is a ragged array. As the
> Updates from NIAC 2016

- base_classes/NXdata.nxdl.xml
An example in the documentation contains a reference to an attribute called `@I_axes`, which suggests that these axes belong to a particular dataset in the NXdata, even though the standard does not mention this case.
Typo?
> NXdata: prefixed axes attribute?

- nxdlTypes.xsd
- utils/dev_units2rst.py
- utils/units2rst.py
The unit categories specified in `nxdlTypes.xsd` have examples when appropriate.  This PR makes the examples machine-readable, as demonstrated by the change in the documentations tool ``utils2rst.py``.  The change will be of benefit to software that will act on the units, such as data file validation software.  Use the UDUNITS-2 library support.  In Python, the cfutils package may be useful.
> for #530: adds machine-readable unit strings

- base_classes/NXevent_data.nxdl.xml
The exiting use at ISIS is floats. We wanted to allow ints.
NX_NUMBER sounds like a sensible compromise.
Don't think we deliberately picked NX_INT.
> allow NX_NUMBER for arrays with times

- base_classes/NXtransformations.nxdl.xml
Rendering of mathematical expressions for transformations in the NxTransformations class definition is broken, see http://download.nexusformat.org/sphinx/classes/base_classes/NXtransformations.html
There seems to be a problem with multiline `math` blocks, these changes work around the problem by reducing them to a single line.
Before fix:
After fix:
> Fix rendering of mathematical expressions for transformations

- base_classes/NXlog.nxdl.xml
fixes #617 
make cue_timestamp_zero a number as intended, not a string
allow NX_NUMBER for time, like in NXevent_data
clarify what a missing @start means in cue_timestamp_zero
> editorial corrections to NXlog

- applications/NXmx.nxdl.xml
- base_classes/NXdetector.nxdl.xml
Putative solution for multi-image masks and a proposed solution to the issues raised here: https://github.com/HDRMX/NXmx/wiki/Treatment-of-(Dynamic)-Shadows-in-Eiger-Data-Sets
Adds this text: Can be either one mask for the whole dataset (rank i, j, k) or each frame can have its own mask (rank np, i, j, k).
Also sync some of the documentation between NXdetector and NXmx.
> Allow multi-image masks. Resolves #651.

- base_classes/NXdisk_chopper.nxdl.xml
~Since the existing `NXdisk_chopper` definitions appeared not to be fit for purpose I have been bold in making breaking changes.~ edit: changes are now non-breaking
Changes follow discussion of requirements for recording chopper data at the ESS.
I think the `delay` description requires further refinement.
> Changes to fields and description of NXdisk_chopper

- manual/source/examples/euler-cif.txt
Fixes #643 
According to http://download.nexusformat.org/sphinx/classes/base_classes/NXtransformations.html transformation axes should be fields of an NXtransformations group, not direct fields of the component to which the transformations apply. This fixes the example shown on the design page of the manual.
I think the `depends_on` field (not attribute) should be in the parent component rather than the `NXtransformations` group, as this results in one fewer operation required when parsing, but this should also be clarified in the documentation.
> Fix NXtransformation example

- applications/NXmx.nxdl.xml
From HDRMX meeting at ACA 2019. 
Co-authored-by: Graeme Winter <graeme.winter@gmail.com>
> NXmx: add NXsource and make name in NXsource and NXinstrument required

- applications/NXmx.nxdl.xml
- base_classes/NXdetector.nxdl.xml
Also sync documentation between NXmx and NXdetector.
Alternate solution to #651 than what I did in #654.  Pending discussion.
> Add per-image dynamic_mask as option for NXdetector. Resolves #651.

- .gitignore
- utils/dev_nxdl2rst.py
- utils/nxdl2rst.py
fixes #562
In some NXDL classes, the name of a field or group is allowed to be flexible at the time the data file is written.  For example, in the definition of `NXdata`, a data field might be allowed any useful name, yet the definition says `data` is its name.  The standard means this is a suggestion.  To be clear when a name is only a suggestion, render it in the manual as upper case; in this case `DATA`.  Names that should be used as shown in the NXDL file will be in lower case.
> Use consistent terms in manual when names are flexible.

- manual/source/datarules.rst
Refs #645
As discussed, documentation for variants as recovered from NIAC Telcos and based on a decision from NIAC 2014.
> Added documentation for variants to datarules.rst

- manual/source/examples/code_napi.rst
- manual/source/examples/h5py/create_data.sh
- manual/source/examples/h5py/index.rst
- manual/source/examples/h5py/writer_1_3.rst
- manual/source/examples/h5py/writer_2_1.rst
- manual/source/faq.rst
- manual/source/utilities.rst
*h5toText* (from spec2nexus) has been changed to *punx tree*.  Change the affected manual pages to fix #705
> adjust links for h5toText, now punx tree

- applications/NXmx.nxdl.xml
- utils/nxdl2rst.py
Extend incident_wavelength to allow per-shot variation 
- Specify how to do monochromatic shot-to-shot variation
- Specify how to do polychromatic shot-to-shot variation
- Include shot-to-shot variation in wavelength spread
Also, py2 bug in nxdl2rst.py.
Fixes #667
> Per shot wavelength, second try

- manual/source/design.rst
The comment on Z is correct, but in ImageCIF, the X axis is defined based on the goniometer orientation. It is common for goniometers to be mounted in different orientations, which will flip X and Y depending on the beamline. Therefore, the second part of the note has been removed.
Fixes #703
> Clarify note on IUCr coordinate system.

- manual/source/datarules.rst
fixes #721
fits into the context of describing uncertainties and errors and the use of the `_errors` suffix
> describe field suffixes reserved by NeXus

- manual/source/design.rst
- manual/source/introduction.rst
- manual/source/rules.rst
- manual/source/strategies.rst
Refs #503
I have updated the information on storing time stamped data in NeXus files. I find this now sufficiently documented.  Some one else, please review and merge. It is now much better then it used to be.
> Improved documentation about time stamped data

- utils/create_release_notes.py
- utils/dev_create_release_notes.py
> Revise release note scripting

- applications/NXmx.nxdl.xml
This is for the NXreflections case where the processed data file could have NXreflections and NXmx sub entries, but the link to the original dataset is gone, therefore there cannot be a NXdata field.
I imagine this one could require a bit more discussion?  Any thoughts on this?  It would be cool to get this into the next milestone too, if possible.
Fixes #746
> From code camp, Make NXmx/NXdata optional.

- applications/NXmx.nxdl.xml
See also nexusformat/cnxvalidate#24
> From code camp, add note to NXmx that file_name and file_time are recommended

- base_classes/NXdata.nxdl.xml
This addition of a`title` field to NXdata and additional documentation fixes #760, where it was asked how to find the plot title in the NeXus data file structure.
> document plot title and axis labels

- applications/NXmx.nxdl.xml
As part of prepping the SwisFEL Jungfrau 1M detector example, @yayahjb moved the beam group from sample to instrument (see [Zenodo entry](https://zenodo.org/record/3526738#.XrNAABNKipr)).  NXbeam is an allowed group on the [NXsample](https://manual.nexusformat.org/classes/base_classes/NXsample.html) and [NXinstrument](https://manual.nexusformat.org/classes/base_classes/NXinstrument.html) base classes so it makes sense to modify [NXmx](https://manual.nexusformat.org/classes/applications/NXmx.html) to make NXbeam optional on sample but note it should be present on one of sample or instrument.
> NXmx: NXbeam can be on sample or instrument

- base_classes/NXuser.nxdl.xml
The ORCID system is widely used in scientific literature to identify authors. This adds the URI as an optional field
> Add ORCID as a field to NXuser

- applications/NXmx.nxdl.xml
beam_center_x and beam_center_y are only used if the depends_on field is not present.   Clarify this and provide a definition of the default geometry given no dependency chain.
> Clarify how beam_center_x and beam_center_y are used

- base_classes/NXdata.nxdl.xml
- manual/source/motivations.rst
DOC #778 concerns what additional attributes will be standardized for plotting from NXdata and the level of detail NeXus will standardize for the default plot.
At NIAC2018, it was decided this documentation was to be added to the manual.
> about simple plotting and NXdata

- applications/NXmx.nxdl.xml
- base_classes/NXdetector.nxdl.xml
- manual/source/datarules.rst
- nxdl.xsd
- utils/nxdl2rst.py
This is the new NXmx Gold Standard as discussed at the raw data e-workshop, 22 August 2020 for
consideration by NIAC.  There is a companion branch for cnxvalidate -- HJB
Includes a fix for #782
> Changes to definitions for NXmx Gold Standard.  Includes changes to NXdl

- base_classes/NXroot.nxdl.xml
Specify NX_DATE_TIME instead of NX_CHAR
closes #783
> NXroot. Use NX_DATE_TIME and not NX_CHAR

- base_classes/NXmonochromator.nxdl.xml
In favor of _errors fields (fixes #820)
> NXmonochromator: deprecate _error fields

- base_classes/NXlog.nxdl.xml
> NXlog: use average_value_errors instead average_value_error

- applications/NXarpes.nxdl.xml
3 fields: **_sensor_size, region_origin_** and **_region_size_** all specified a **_rank_** but did not then specify the required **_dim_** fields as well, this pull request adds the missing dim fields so that the nxdl can be auto generated as well as pass **cnxvalidate**.
> Added missing required dim fields

- manual/source/design.rst
Fixes #841 as directed by [NIAC2018](https://www.nexusformat.org/NIAC2018Minutes.html#decision_target), note the `target` attribute does not work for external file links.
> DOC: note the `target` attribute does not work for external file links

- base_classes/NXreflections.nxdl.xml
Fixes #724
Considered deprecating the _var fields but I'm not convinced there is a need too, even though the spec did get a bit busy through this change.
> Add _errors to NXreflections

- applications/NXfluo.nxdl.xml
- applications/NXindirecttof.nxdl.xml
- applications/NXiqproc.nxdl.xml
- applications/NXlauetof.nxdl.xml
- applications/NXmonopd.nxdl.xml
- applications/NXmx.nxdl.xml
- applications/NXrefscan.nxdl.xml
- applications/NXreftof.nxdl.xml
- applications/NXsas.nxdl.xml
- applications/NXsastof.nxdl.xml
- applications/NXscan.nxdl.xml
- applications/NXsqom.nxdl.xml
- applications/NXstxm.nxdl.xml
- applications/NXtas.nxdl.xml
- applications/NXtofnpd.nxdl.xml
- applications/NXtofraw.nxdl.xml
- applications/NXtofsingle.nxdl.xml
- applications/NXtomo.nxdl.xml
- applications/NXtomophase.nxdl.xml
- applications/NXtomoproc.nxdl.xml
- applications/NXxas.nxdl.xml
- applications/NXxasproc.nxdl.xml
- applications/NXxbase.nxdl.xml
- applications/NXxeuler.nxdl.xml
- applications/NXxkappa.nxdl.xml
- applications/NXxlaue.nxdl.xml
- applications/NXxnb.nxdl.xml
- applications/NXxrot.nxdl.xml
- base_classes/NXdisk_chopper.nxdl.xml
also a standard is proposed for a symbol naming convention as many definitions refer to a similar symbol "meaning" but the naming was arbitrary, number of points for example (nP, numP, NumP etc).
Fixes #800, fixes #786, fixes #787, fixes #788
> Symbol tables were added to def's that did not have them

- .github/workflows/syntax-checks.yml
- .github/workflows/unit-tests-pytest.yml
- environment.yml
> Move CI from travis-ci to Github Actions

- manual/source/nxdl-types.rst
- nxdlTypes.xsd
State in the manual that NX_CHAR is the default field type, to reflect the existing NXDL behaviour. This change only documents current behaviour and fixes #892.
> State in the manual that NX_CHAR is the default field type

- manual/source/nxdl.rst
- utils/nxdl2rst.py
The tip shown below is out of place as it appears on every NXDL documentation web page.  Relocate it to fix #923.
> remove tip at bottom of every NXDL , place it on NXDL chapter page

- .github/env-workflow.yml
- .github/workflows/syntax-checks.yml
- nxdl.xsd
- utils/nxdl_desc2rst.py
> repair workflow and make Python code compliant with py3

- base_classes/NXentry.nxdl.xml
- base_classes/NXsubentry.nxdl.xml
To FIX #916, change the documentation field of the `@default` attribute to point to the manual page describing how NeXus describes the default plottable data.  Currently, the documentation points to the NIAC2014 discussion of the topic.
> in NXentry & NXsubentry, link to manual page instead of discussion

- contributed_definitions/NXcsg.nxdl.xml
For NXDL class summaries, only first line of doc block will be used.  Revise obvious content to fit.
> DOC doc string all on one line

- applications/NXspe.nxdl.xml
removed the invalid NX_SPE from the definition field enumeration list because it does not point to a valid NXDL schema, fixes #911 :
```
<enumeration>
<item value="NXSPE"/>
<item value="NXspe"/>                
</enumeration>
```
is now 
```
<enumeration>
<item value="NXspe"/>                
</enumeration>
```
> removed NX_SPE from the definition fields enumeration list

- contributed_definitions/NXxpcs.nxdl.xml
- Close #1005
On review of the equation for g2, the units are identical in numerator and denominator. The correct unit type for this is `NX_DIMENSIONLESS`.
@ambarb @AbbyGI @JulReinhardt - can you comment?
> change g2 unit type to NX_DIMENSIONLESS

- nxdlTypes.xsd
Closes #1075 
Before the fix:
After the fix:
> NX_COUNT was missing from the unit categories

- contributed_definitions/NXxpcs.nxdl.xml
This is processed data, so it needs a [NXprocess](https://manual.nexusformat.org/classes/base_classes/NXprocess.html#nxprocess) group to document details of the reconstruction process.
- Close #1006
@ambarb @AbbyGI @JulReinhardt - can you comment?
> NXxpcs: add NXprocess group

- base_classes/NXdetector.nxdl.xml
When accepting NXtomo we accidentally introduced the `image_key` field to `NXdetector`. This is not only useful for tomography, but can be used in all cases, where various calibrations are interspersed with "normal" exposures of the sample. It preserves the sequence of the measurements are taken and does not require any (implied) protocol. 
Since this is already part of NeXus and in active use, through NXtomo, this should relatively non-contentious.
> add image_key to NXdetector

- manual/source/Makefile
- manual/source/classes/applications/Makefile
- manual/source/classes/base_classes/Makefile
- manual/source/classes/contributed_definitions/Makefile
Closes #1078 
It seems that doing `python ... > file.ext` in make files could result in `file.ext` to be incomplete.
The solution seems to be unbuffered stdout: `python -u ... > file.ext`
> use unbuffered stdout for python in make files

- base_classes/NXdetector.nxdl.xml
fixes #590 by expanding doc strings to explain that the displayed dataset dimensions are only illustrative. The symbols used have also been made more consistent.
> 590 nxdetector dimensions

- nxdlTypes.xsd
- utils/dev_units2rst.py
- utils/units2rst.py
added NX_CCOMPLEX, NX_PCOMPLEX. NX_COMPLEX, and NX_QUATERNION
* closes #1056
> NX_COMPLEX - Update nxdlTypes.xsd

- base_classes/NXfilter.nxdl.xml
- nxdl.xsd
- Fixes #963 
- close nexusformat/NIAC#112. 
Also remove from NXfilter's coating_roughness field (which was add in 20090304 by change f86bdcb4591707db84346207dbbc49297c75c8a0)
> Deprecate incr attribute of dimension type

- manual/source/defs_intro.rst
resolves #1000, a more explicit description of the symbols table is given along with some examples to help clarify those descriptions.
> added more specific guidelines to symbols intro definition

- manual/source/utilities.rst
> add NeXus Constructor and nxdl_to_hdf5.py

- utils/units2rst.py
- fixes #979 
a single newline character was ignored during conversion to html, new line with a tab worked and rendered it looks ok
> adjust string for examples so they appear on new lines

- utils/nxdl2rst.py
Closes #936 This does not change the meaning of the `dimensions` xml tag but rather the rst rendering. Problems with the original rendering:
* some users were using for example `"field[n]"` as the HDF5 dataset name instead of `"field"`
* rendering sometimes gave the wrong idea about rank symbol and/or dimensions symbols (e.g. the DATA fiield of NXdata, see bellow)
These are the different dimensions that can occur:
```xml
<field name="data" type="NX_INT" signal="1">
<dimensions rank="3">
<dim index="1" value="nP" />
<dim index="2" value="xDim" />
<dim index="3" value="yDim" />
</dimensions>
</field>
```
[NXscan example](https://manual.nexusformat.org/classes/applications/NXscan.html#nxscan-entry-instrument-detector-data-field)
Old rendering
New rendering
```xml
<field name="data" …
```
> improve the 'dimensions' tag rst rendering

- utils/nxdl2rst.py
Closes #1101 
* Fix bug: when rank was missing, it was set to the number of dimensions, even when some dimensions were optional.
* Change: a variable rank without symbol was shown as `Rank: .`, now we simply omit the rank
* Add rank and dimension checks. They all pass for the existing classes.
> Fix rank bug + add checks

- base_classes/NXbeam.nxdl.xml
Fixes #925. Add optional depends_on field and NXtransformations group to override the default choice of the beam direction along positive z and passing through the origin
Also closes https://github.com/nexusformat/NIAC/issues/115
> Add geometry information to NXbeam for #925

- utils/nxdl2rst.py
- close #1108
As described by @sanbrock
> Table of Hypertext Anchors just needs first column 

- manual/source/utilities.rst
https://github.com/nexusformat/definitions/blob/2afc7f8a536251f0645db06611a4a64918da15c5/manual/source/validation.rst#L57
https://github.com/nexusformat/definitions/blob/918df5e60130e8c1d8c5d3a6b2c2eec0128533c1/manual/source/utilities.rst#L163
> _punx target already exists

- utils/nxdl2rst.py
Closes #1162 
The main branch had this after #1151
That is wrong. The status should mention the category (base or application definition). This PR fixes it back to how it was
Originally we had this
```python
listing_category = {
"base": "base class",
"application": "application definition",
"contributed": "contributed definition",
}[subdir]
```
which then changed in #1151 to this
```python
listing_category = {
"base_classes": "base class",
"applications": "application definition",
"contributed_definitions": "contributed definition",
}[nxdl_subdir]
```
Seems legit. The problem however is the `subdir` was in fact NOT the directory name, it was the category! So the name of that variable threw us off. Note that the category is never `contributed` so we always had either `base class` or …
> Listing category is either "base class" or "application definition"

- base_classes/NXtransformations.nxdl.xml
This is an arbitrary identifier of a component of the equipment to which the transformation belongs, such as 'detector_arm' or 'detector_module'. NXtransformations with the same equipment_component label form a logical grouping which can be combined together into a single change-of-basis operation.
Ported in from ImageCIF:
http://www.bernstein-plus-sons.com/software/CBF/doc/cif_img_1.8.4.html#_axis.equipment_component
> Add equipment_component to NXtransformations

- applications/NXmx.nxdl.xml
This is copied in from NXdetector_module
Noticed when reviewing NXmx that it would be good to exactly state how to specify the pixel size, like we do for the base class.
> Clarify pixel size in NXmx

- applications/NXmx.nxdl.xml
- base_classes/NXdetector.nxdl.xml
We use virtual pixels to account for the space in between chips. For that, the edge pixels of the chips are extended into the gaps, creating more counts on those edges.The virtual pixel correction distributes these counts over the logical pixels.
> NXdetector: Add virtual_pixel_correction_applied

- applications/NXxas.nxdl.xml
fixes #1170 with minimal changes.
> 1170 nxxas documentation improvement

- base_classes/NXdata.nxdl.xml
Closes #1044 
Currently [`NXdata`](https://manual.nexusformat.org/classes/base_classes/NXdata.html) does not allow errors on auxiliary signals.
This PR solves that by
* renaming the `VARIABLE` field to `AXISNAME`
* updating the doc of `VARIABLE_errors` to say it applies to axes, signal or auxiliary signals: this is the actual change, although it is already somewhat support by NeXus as described [here](https://manual.nexusformat.org/datarules.html?highlight=errors).
* deprecate `errors` in favor of `VARIABLE_errors`  for the signal field
> NXdata errors on an axis, signal or auxiliary signal

- applications/NXsas.nxdl.xml
- close #522
- close https://github.com/nexusformat/NIAC/issues/58
> NXsas: review minOccurs and group names

- nxdl.xsd
It is allowed for fields and groups to be recommended.
However, this is not allowed for attributes.
This PR allows recommended setting for attributes as well.
- close https://github.com/nexusformat/NIAC/issues/140
> Allowing the recommended xml attribute for nexus attributes

- .github/workflows/ci.yaml
Closes 
- #1029
- #1199
- #1200
After this MR
1. the CI runs **without deployment** for every pull request to the main branch and push (tags or commits) to the master branch
2. the CI can only run **with deployment** when triggered manually, with "Deploy documentation" enabled, similar to [this](https://www.softwaretester.blog/detecting-github-workflow-job-run-status-changes).
> Deploy by running CI manually

- base_classes/NXdata.nxdl.xml
Closes #1209 
Improved docs to clearly state that the strings in @signal, @auxiliary_signals, @axes refer to
* fields or links
* direct children of the NXdata group
* must exist
> NXdata: @signal, @auxiliary_signals and @axes refer to direct NXdata children

- applications/NXmx.nxdl.xml
- Updates saturation/underload to use NX_NUMBER
- Clarifies countrate_correction_applied and adds countrate_correction_lookup_table
Both are recent changes to NXdetector
Fixes #1215
> Sync saturation and countrate to NXmx

- base_classes/NXsource.nxdl.xml
Simple change for consistency, following Zoom discussion.
> "Electron Source" rather than "Electron Microscope"

- dev_tools/nxdl/syntax.py
Closes #1266 
After this PR, the following error messages are produced
```xml
<group type="NXtransformations" forbidden="forbidden">
...
</group>
```
```
E           dev_tools.globals.errors.XMLSyntaxError: 
E             .../definitions/base_classes/NXaperture.nxdl.xml
E             Element '{http://definition.nexusformat.org/nxdl/3.1}group', attribute 'forbidden': 
E             The attribute 'forbidden' is not allowed., line 51
```
```xml
<group type="NXtransformations"
...
</group>
```
```
E           dev_tools.globals.errors.XMLSyntaxError: 
E             .../definitions/base_classes/NXaperture.nxdl.xml
E             error parsing attribute name, line 52, column 7 (NXaperture.nxdl.xml, line 52)
```
> XML errors: make file and line more clear

- base_classes/NXbeam.nxdl.xml
Add documentation about cases where NXbeam is defined as a subgroup directly inside a NXinstruments group.
Closes #1263
> NXbeam: clarify how beams can be in either sample or instrument groups

- pyproject.toml
This fixes a typo which resulted in setuptools-scm not being able to resolve the version (was always 0.0.0).
It also enables `no-guess-dev`, i.e. no new versions are guessed from the current ones, as this makes no sense for date based versioning.
> Fixes automatic versioning

- applications/NXcanSAS.nxdl.xml
- base_classes/NXdata.nxdl.xml
- base_classes/NXlog.nxdl.xml
- base_classes/NXmonitor.nxdl.xml
Closes #1212
In this PR we refactor the NXdata definition to resolve inconsistencies in definition of `@axes`, `AXISNAME_indices` and `AXISNAME`. NIAC discussions:
* [Telco_20230314](https://github.com/nexusformat/wiki/blob/master/content/Telco_20230314.md):  illustrate the problem with the current definition [2023_03_niac.pdf](https://github.com/nexusformat/definitions/files/10972084/2023_03_niac.pdf)
* [Telco_20230419](https://github.com/nexusformat/wiki/blob/master/content/Telco_20230419.md): provide answers to https://github.com/nexusformat/definitions/issues/1212#issuecomment-1514871682 and https://github.com/nexusformat/definitions/issues/1212#issuecomment-1499970433
The proposed changes do not change anything to the current NXdata, they just clear up ambiguity:
* …
> NXdata: improve documentation regarding axes

- .gitignore
- Makefile
- README.md
- nyaml.mk
- requirements.txt
This adds several things:
- Proper build of `nxdl.xml` files even if they are not present. This is now completely based on the available yaml files
- Removal of `nyaml` for loop
- Add a new Makefile `nyaml.mk` for building nyaml targets to be invoked like this `make -f nyaml.mk`
- [nyaml](https://github.com/FAIRmat-NFDI/nyaml) as a dependency to provide the `nyaml2nxdl` command. [Here](https://pypi.org/project/nyaml/) is the pypi page of nyaml.
> Adds makefile refinements and nyaml as dependency

- dev_tools/docs/nxdl.py
- dev_tools/tests/NXtest.nxdl.xml
- dev_tools/tests/test_nxdl_utils.py
- dev_tools/utils/nxdl_utils.py
- manual/source/conf.py
- requirements.txt
> adding links to first references of the vocabulary items and support for collapsing doc strings

- .github/workflows/ci.yaml
The current CI/CD does not setup the different python version and just sets the `python-version` environment variable. I added a step to set the python version to the one of the current matrix element.
Fixes #1317
> Adds setup python step in CI/CD

- base_classes/NXaperture.nxdl.xml
- NXaperture was marked as deprecated but it is not, so fix the documentation
- Explicitly add an unnamed NXoff_geometry field, the existence of which was implied by the GEOMETRY deprecation
Fixes #1231
> Fix documentation of NXaperture

- utils/create_release_notes.py
This is better than last_modified as that can be altered with milestone changes. Also use last_modified_datetime and remove helper function
> Change pull requests dates to when they are closed

- applications/NXindirecttof.nxdl.xml
"a direct" changed to "an indirect" in the description of `NXindirecttof`.
> Description of `NXindirecttof`

- base_classes/NXparameters.nxdl.xml
- base_classes/NXtransformations.nxdl.xml
- close #1401
@ndevenish - Thanks for reporting this!
> "term" should be all caps (indicates it is a flexible name)

- nxdlTypes.xsd
Idea is to state that NX_CHAR is a string of characters, and remove the other documentation that doesn't seem as necessary nowadays.
Fixes #1441
> Greatly simplify the NX_CHAR documentation

- .gitignore
- CHANGES.rst
- applications/NXcanSAS.nxdl.xml
- base_classes/NXdata.nxdl.xml
- dev_tools/docs/nxdl.py
- dev_tools/utils/nxdl_utils.py
- manual/source/conf.py
- manual/source/datarules.rst
- nxdl.xsd
- requirements.txt
> UPPERCASE to indicate flexible names

- manual/source/nxdl-types.rst
- nxdl.xsd
- nxdlTypes.xsd
> complex units, such as eV/mm

- base_classes/NXcollection.nxdl.xml
> emphasize NXcollection is not validated

- manual/source/examples/epics/index.rst
> show how to validate an XML file

- applications/NXarchive.nxdl.xml
- applications/NXarpes.nxdl.xml
- applications/NXdirecttof.nxdl.xml
- applications/NXfluo.nxdl.xml
- applications/NXindirecttof.nxdl.xml
- applications/NXiqproc.nxdl.xml
- applications/NXlauetof.nxdl.xml
- applications/NXmonopd.nxdl.xml
- applications/NXrefscan.nxdl.xml
- applications/NXreftof.nxdl.xml
- applications/NXsastof.nxdl.xml
- applications/NXsqom.nxdl.xml
- applications/NXtas.nxdl.xml
- applications/NXtofnpd.nxdl.xml
- applications/NXtofraw.nxdl.xml
- applications/NXtofsingle.nxdl.xml
- applications/NXtomo.nxdl.xml
- applications/NXtomophase.nxdl.xml
- applications/NXtomoproc.nxdl.xml
- applications/NXxas.nxdl.xml
- applications/NXxasproc.nxdl.xml
- applications/NXxbase.nxdl.xml
- applications/NXxeuler.nxdl.xml
- applications/NXxkappa.nxdl.xml
- applications/NXxlaue.nxdl.xml
- applications/NXxlaueplate.nxdl.xml
- applications/NXxnb.nxdl.xml
- applications/NXxrot.nxdl.xml
- contributed_definitions/NXxpcs.nxdl.xml
- Change all instances of <group type="NXentry" name="entry"> to <group type="NXentry"> (24 instances)
- Deprecate all instances of <attribute name="entry"> (6 instances)
Fixes #1438
This was voted on in [NIAC 2024](https://www.nexusformat.org/content/NIAC2024_minutes/#session-e-sept-28th-1330-utc) so this only needs a review from @nexusformat/developers
> Remove limitation on how entries are named

- manual/source/design.rst
- manual/source/faq.rst
- Adds section on "Inheritance in NeXus" to design.rst
- Changes "In contrast to NeXus base classes, NeXus supports inheritance in application definitions." to "Like base classes, NeXus supports inheritance in application definitions."
- Rewrites the FAQ question on inheritance
Notably, I left this paragraph alone in design.rst, as I didn't think that discussion needed to be cluttered by inheritance and that it didn't contradict the use of inheritance:
> NeXus base classes are not proper classes in the same sense as used in object oriented programming languages. In fact the use of the term classes is actually misleading but has established itself during the development of NeXus. NeXus base classes are rather dictionaries of field names and their meanings which are permitted in a …
> Permit simple inheritance for base classes

- manual/source/examples/epics/attributes-reformatted.xml
- manual/source/examples/epics/attributes.xml
While working on https://github.com/areaDetector/ADCore/issues/512, found the example file did not validate as expected.  Correct a minor typo (`datatype` -> `dbrtype`) and revise the example to show a macro expansion (https://github.com/areaDetector/ADCore/pull/522).
> Apply corrections and update EPICS area detector attributes example

- base_classes/NXobject.nxdl.xml
- manual/source/datarules.rst
Implements vote in https://github.com/nexusformat/definitions/issues/1451#issuecomment-2382523273.
Depends on https://github.com/nexusformat/definitions/pull/1485 -> done
Any implementation should consider comments in https://github.com/nexusformat/definitions/pull/1416
> add identifierNAME to NXobject

- applications/NXmx.nxdl.xml
Fixes #1511
The vibe from the telco where this was discussed was that this doesn't need a vote since it's a bugfix.
> NXmx: make NXdetector_channel optional

- .github/workflows/ci.yaml
- dev_tools/tests/test_nxdl_utils.py
`actions/upload-artifact@v3` is [deprecated as of Jan 30](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/). This updates to v4.
@PeterC-DLS would you be able to review this? All builds in the other branches are failing because of the deprecation.
This PR also contains a change to `dev_tools/tests/test_nxdl_utils.py` that comes from using a newer version of black (as black is not pinned in this repo).
> update ci.yaml to use actions/upload-artifact@v4, black format

- base_classes/NXcalibration.nxdl.xml
- base_classes/NXhistory.nxdl.xml
- base_classes/NXtransformations.nxdl.xml
Fixes the `nameType`  for four different concepts:
- NXtransformations/AXISNAME_end -> was nameType="any", should be nameType="partial"
- NXtransformations/AXISNAME_increment -> was nameType="any", should be nameType="partial"
- NXhistory/identifierName -> has no nameType, should be nameType="partial"
- NXcalibration/identifierName -> has no nameType, should be nameType="partial"
For the fields in NXtransformations, this was probably a copy-paste error. For NXhistory and NXcalibration, which were recently added by me, it was simply forgotten to add the `nameType`.
> `nameType="partial"` fixes for some base classes

- nxdl.xsd
optional is only a synonym for minOccurs=0 when optional=true.
When optional is false, this must mean the opposite so minOccurs>0 since nonNegativeUnbounded (not specifying the exact value of minOccurs, we only know it is greater than 0).
> XDS: clarify the definition of the optional attribute in relation to minOccurs for fields and groups

- base_classes/NXtransformations.nxdl.xml
There was a long-ish [discussion](https://github.com/nexusformat/definitions/pull/1415#discussion_r2075856637) in #1415 about which rotation convention to apply for left- and right-handed coordinate systems. Initially, it was agreed that if the `NXtransformation` depends on a coordinate system (i.e., its ``depends_on`` attribute points to an instance `NXcoordinate_system`), the rotation is **always** right handed in that coordinate system, even if the the coordinate system itself is left-handed (as defined by the determinant of its base vectors.
@PeterC-DLS suggested that this should not be the case. Rather, the rotation conventions **should** follow the handedness of the coordinate system because then the matrices don't have to be changed. So:
- Rotations in left-handed coordinate …
> Clarify the conventions for rotations in left and right handed coordinate system

- base_classes/NXbeam.nxdl.xml
Also add note on beam direction being referenced by a depends_on
> Remove extraneous transformation type attributes from beam directions

- applications/NXxps.nxdl.xml
This fixes the units in `NXxps/NXbeam/beam_direction` such that they match with the [recently changed](https://github.com/nexusformat/definitions/pull/1562) units `NXbeam/BEAMdirection`.
@PeterC-DLS I hadn't realized you had changed the units in `NXbeam` as well. This should be an easy bug fix not requiring a vote.
> [Bug fix] Units in `NXxps/NXbeam/beam_direction`

- applications/NXarchive.nxdl.xml
- applications/NXcanSAS.nxdl.xml
- applications/NXdirecttof.nxdl.xml
- applications/NXlauetof.nxdl.xml
- applications/NXmx.nxdl.xml
- base_classes/NXattenuator.nxdl.xml
- base_classes/NXcomponent.nxdl.xml
- base_classes/NXdata.nxdl.xml
- base_classes/NXdetector.nxdl.xml
- base_classes/NXentry.nxdl.xml
- base_classes/NXhistory.nxdl.xml
- base_classes/NXlog.nxdl.xml
- base_classes/NXpdb.nxdl.xml
- base_classes/NXpid_controller.nxdl.xml
- base_classes/NXresolution.nxdl.xml
- base_classes/NXsample.nxdl.xml
- base_classes/NXsensor.nxdl.xml
- base_classes/NXsubentry.nxdl.xml
- base_classes/NXtransformations.nxdl.xml
Fixing typos that we spotted on the FAIRmat side given that we use cspell as a spellchecker. These typos were observed when comparing of the FAIRmat-NFDI fairmat branch 1e8c433 with NIAC main ecc9361
> Fixing typos in appdefs and baseclasses, removal of concepts that are now coming for free cuz of inheritance

- applications/NXapm.nxdl.xml
- applications/NXem.nxdl.xml
- base_classes/NXaberration.nxdl.xml
- base_classes/NXapm_event_data.nxdl.xml
- base_classes/NXapm_instrument.nxdl.xml
- base_classes/NXapm_measurement.nxdl.xml
- base_classes/NXapm_reconstruction.nxdl.xml
- base_classes/NXcorrector_cs.nxdl.xml
- base_classes/NXebeam_column.nxdl.xml
- base_classes/NXem_ebsd.nxdl.xml
- base_classes/NXem_event_data.nxdl.xml
- base_classes/NXem_instrument.nxdl.xml
- base_classes/NXem_measurement.nxdl.xml
- base_classes/NXphase.nxdl.xml
- manual/source/classes/contributed_definitions/NXem.TopLevelDoc.FIB.svg
- manual/source/classes/contributed_definitions/NXem.TopLevelDoc.SEM.svg
- manual/source/classes/contributed_definitions/NXem.TopLevelDoc.TEM.svg
- manual/source/classes/contributed_definitions/apm-structure.rst
- manual/source/classes/contributed_definitions/em-structure.rst
- Bringing FAIRmat's PR402 (Ray's comments on renaming EM base classes) that was discussed in #1423 to the `main`
- Fixing a few bugs on the NXapm appdef
> Fairmat addition pr402 to em
